from typing import Sequence

class ShaderNoiseTexture:
    freq: int = ...
    width: int = ...
    data: Sequence[int] = ...
    def __init__(self, freq: int = ..., width: int = ...) -> None: ...
    def load(self) -> None: ...
    def enable(self) -> None: ...

shader_noise_glsl: str
