import unittest

class PerlinTestCase(unittest.TestCase):
    def test_perlin_1d_range(self) -> None: ...
    def test_perlin_1d_octaves_range(self) -> None: ...
    def test_perlin_1d_base(self) -> None: ...
    def test_perlin_2d_range(self) -> None: ...
    def test_perlin_2d_octaves_range(self) -> None: ...
    def test_perlin_2d_base(self) -> None: ...
    def test_perlin_3d_range(self) -> None: ...
    def test_perlin_3d_octaves_range(self) -> None: ...
    def test_perlin_3d_base(self) -> None: ...

class SimplexTestCase(unittest.TestCase):
    def test_simplex_2d_range(self) -> None: ...
    def test_simplex_2d_octaves_range(self) -> None: ...
    def test_simplex_3d_range(self) -> None: ...
    def test_simplex_3d_octaves_range(self) -> None: ...
    def test_simplex_4d_range(self) -> None: ...
    def test_simplex_4d_octaves_range(self) -> None: ...
